blank_issues_enabled: false
contact_links:
  - name: Support VAUNTCORP sur Discord
    url: https://discord.gg/66khxqRVvd
    about: Obtenir de l'aide pour la configuration ou l'utilisation de VAUNTCORP MDT.
